# Generated by Django 4.0.5 on 2022-06-29 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_avatar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(blank=True, default='static_media/user.png', null=True, upload_to='articles'),
        ),
    ]
