# Generated by Django 4.0.5 on 2022-06-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_avatar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='static_media/user.png', null=True, upload_to='articles'),
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
