# Generated by Django 4.0.5 on 2022-07-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_profile_avatar_delete_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='../newsapp/static/img/user.png', null=True, upload_to='articles'),
        ),
    ]
