# Generated by Django 4.0.5 on 2022-07-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0011_voteitem_article_voteitem_comment_voteitem_reply'),
        ('accounts', '0017_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='award',
            field=models.ManyToManyField(blank=True, to='newsapp.awarditem'),
        ),
    ]
