# Generated by Django 4.0.4 on 2022-05-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='animation',
            field=models.CharField(blank=True, choices=[('rotate', 'Rotate'), ('glow', 'Glow'), ('shake', 'Shake')], max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='comment',
            field=models.ManyToManyField(blank=True, to='newsapp.comment'),
        ),
    ]
