# Generated by Django 4.0.5 on 2022-06-07 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsapp', '0002_award_animation_alter_article_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(choices=[('a', 'Article'), ('c', 'Comment'), ('r', 'Reply'), ('s', 'SubReply')], max_length=1)),
                ('parent_id', models.PositiveIntegerField()),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
