# Generated by Django 4.0.5 on 2022-06-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_voteitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteitem',
            name='choice',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='voteitem',
            name='parent',
            field=models.CharField(choices=[('a', 'Article'), ('c', 'Comment'), ('r', 'Reply')], max_length=1),
        ),
    ]
