# Generated by Django 4.0.5 on 2022-06-11 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_voteitem_choice_alter_voteitem_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteitem',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsapp.article'),
        ),
        migrations.AddField(
            model_name='voteitem',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsapp.comment'),
        ),
        migrations.AddField(
            model_name='voteitem',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsapp.reply'),
        ),
    ]
