# Generated by Django 4.0.5 on 2022-06-27 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0008_alter_customuser_options_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
