# Generated by Django 4.0.5 on 2022-06-29 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0009_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voteitem',
            name='article',
        ),
        migrations.RemoveField(
            model_name='voteitem',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='voteitem',
            name='reply',
        ),
    ]
