# Generated by Django 4.0.5 on 2022-07-01 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0011_voteitem_article_voteitem_comment_voteitem_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awarditem',
            old_name='award_quantity',
            new_name='quantity',
        ),
    ]
