# Generated by Django 4.0.5 on 2022-07-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0012_rename_award_quantity_awarditem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='recipent',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
