# Generated by Django 4.0.5 on 2022-07-09 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0013_reply_recipent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteitem',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsapp.article'),
        ),
        migrations.AlterField(
            model_name='voteitem',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsapp.comment'),
        ),
        migrations.AlterField(
            model_name='voteitem',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsapp.reply'),
        ),
    ]
