# Generated by Django 4.0.5 on 2022-07-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0014_alter_voteitem_article_alter_voteitem_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='anon_id',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
