# Generated by Django 4.0.5 on 2022-07-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0015_comment_anon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='anon_id',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='anon_id',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
