# Generated by Django 4.0.5 on 2022-07-12 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsapp', '0017_remove_comment_award_remove_reply_award_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awarditem',
            name='type',
        ),
        migrations.AddField(
            model_name='awarditem',
            name='anon_id',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='awarditem',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
