# Generated by Django 4.0.5 on 2022-07-14 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0022_awarditem_anon_id_awarditem_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anon_id', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('status', models.CharField(blank=True, default='processing', max_length=20)),
                ('email', models.EmailField(default='guest', max_length=254)),
                ('price', models.PositiveIntegerField(blank=True, default=0)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.award')),
            ],
        ),
    ]
