# Generated by Django 4.0.6 on 2022-09-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0023_awardtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capital', models.CharField(max_length=50)),
                ('continent', models.CharField(max_length=50)),
                ('iso', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='award',
            name='animation',
            field=models.CharField(blank=True, choices=[('rotate', 'Rotate'), ('glow', 'Glow'), ('shake', 'Shake'), ('spin', 'Spin')], max_length=50),
        ),
        migrations.AlterField(
            model_name='awardtransaction',
            name='email',
            field=models.EmailField(default='guest@email.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='awardtransaction',
            name='status',
            field=models.CharField(blank=True, default='initialized', max_length=20),
        ),
    ]
