# Generated by Django 4.0.6 on 2022-09-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0026_article_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.URLField(null=True),
        ),
    ]
