# Generated by Django 4.1.1 on 2022-09-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0031_alter_article_date_alter_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[('news', 'News'), ('beauty', 'Beauty')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reply',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
