# Generated by Django 4.1.1 on 2022-09-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0033_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[('news', 'News'), ('blog', 'Blog'), ('products', 'Products')], max_length=50),
        ),
    ]
